### ISSUE TITLE
option: reverse order for blocks columns

### ISSUE THREAD

**Issue by mmaulwurff** [mmaulwurff/gearbox#25]
Submitted by ghostboy1225 on [ZDF](https://forum.zdoom.org/viewtopic.php?f=43&t=71086&sid=5ec7e1bbf5e1fad6bfc191a0faf88104&p=1218930#p1218930):
> is there some way we could see bucket styled layout inverted as an option to allow those wanting HL style weapon buckets. currently you start at the bottom of the bucket and make your way up rather than starting at the top and working your way down like in HL. great mod works pretty good with HD.

**Comment by Carrascado** [comment]
I guess this could be marked as solved? @mmaulwurff And notifying ghostboy1225 through ZDF.

I'm pretty sure his suggestion meant what I added in the PR.

**Comment by mmaulwurff** [comment]
I guess it is. Solved by #31.
