### ISSUE TITLE
Frozen solid

### ISSUE THREAD

**Issue by Linzmouse** [mmaulwurff/gearbox#26]
I found an interesting bug: Entering a new map with the weapon wheel open will cause  all your movement to be stuck

I don't think this is a really big issue, only would happened if you'd like use the console to change maps but I figured I should let you know anyway

**Comment by mmaulwurff** [comment]
Cannot reproduce. Tried both with and without mouse input enabled, both freeze options (player and player+enemies).

I'll need more specific information on this. It would be great to have your ini file.
