### ISSUE TITLE
Gearbox v0.7.2 lzdoom version

### ISSUE THREAD

**Issue by abdogm** [mmaulwurff/gearbox#37]
Not that big deal but I'd like to ask if there is any chance to have lzdoom version of the latest gearbox ?

**Comment by generic-name-guy** [comment]
No

**Comment by mmaulwurff** [comment]
Gearbox requires some function attributes that are not present in LZDoom. Creating a version for LZDoom would require removing the wheel and creating a separate .pk3, which is too much work.

It should be fairly trivial to make Gearbox work with LZDoom by commenting out functions on which LZDoom errors out, I won't create a special version for that.
