### ISSUE TITLE
can't load the mod in gzdoom 4.14

### ISSUE THREAD

**Issue by liPillON** [mmaulwurff/gearbox#48]
pasting only the relevant log entries

> GScript error, "gearbox.pk3:zscript/gearbox/weapon_menu.zs" line 292:
> GCannot convert SInt4 to TextureID
> GScript error, "gearbox.pk3:zscript/gearbox/weapon_menu.zs" line 314:
> GCannot convert SInt4 to TextureID
> GScript error, "gearbox.pk3:zscript/gearbox/inventory_menu.zs" line 107:
> GCannot convert SInt4 to TextureID
> 
> Execution could not continue.
> 3 errors while parsing scripts

this is related to recent changes in how gzdoom handles arrays -- with 4.14 they were extended to all zscript versions due to security/vulnerabilities concerns
reference: https://discord.com/channels/268086704961748992/392006099462651906/1319621363962482688

the issue has been discussed on zdoom's discord
starting here: https://discord.com/channels/268086704961748992/340199158772269056/1318693652494553129
ending here: https://discord.com/channels/268086704961748992/340199158772269056/1318698291076268082

and on zdoom's forums
https://forum.zdoom.org/viewtopic.php?t=79987

**Comment by 63564365** [comment]
It's been fixed in pull request #47
