### ISSUE TITLE
Enemies not freezing on Project Brutality 3.0

### ISSUE THREAD

**Issue by Matty4818** [mmaulwurff/gearbox#7]
I’ve tried your current weapon wheel version along with some older ones on Project Brutality 3.0 and when I try to turn the option on for freezing both player and enemies, the enemies continue to fire at me. I’m using the current gzdoom 4.5 and I have tried this weapon wheel on 2 different Project Brutality 3.0 branches. I tried your weapon wheel on Brutal Doom v21 and it was able to freeze both me and the enemies but it will not freeze the enemies on Project Brutality. Hopefully you can give me some insight into why this isn’t working. Thank you!

**Comment by JMartinez9820** [comment]
@Matty4818 Please read the Readme.md next time before reading this. It does state that time freeze cvar PyWheel, which is implemented in Project Brutality, needs to be turned off, or else it overrides with Gearbox's time freeze cvar.

From Readme.md:
Compatibility Issues
PyWeaponWheel v0.3 overrides time freezing. If you are using both mods and want to freeze time with Gearbox, set PyWeaponWheel's option "Freeze when wheel is open" (py_weaponwheel_freeze CVar) to Off.

Note that PyWeaponWheel may be built in some mods, for example in Project Brutality. The solution is the same: disable time PyWeaponWheel's time freezing.


Off-topic, but the PB team does plan to possibly also replace PyWheel with Gearbox as the weapon special wheel in the future.

**Comment by JMartinez9820** [comment]
@Matty4818  Next time, please read the Readme.md next time before posting this. It does state that PyWheel, which is implemented in Project Brutality, needs the freeze time option turned off, or else it overrides with Gearbox's time freeze option.

From Readme.md:
Compatibility Issues
PyWeaponWheel v0.3 overrides time freezing. If you are using both mods and want to freeze time with Gearbox, set PyWeaponWheel's option "Freeze when wheel is open" (py_weaponwheel_freeze CVar) to Off.

Note that PyWeaponWheel may be built in some mods, for example in Project Brutality. The solution is the same: disable time PyWeaponWheel's time freezing.

Off-topic, but the PB team does plan to possibly also replace PyWheel with Gearbox as the weapon special wheel in the future.

**Comment by Matty4818** [comment]
Please forgive me, I did read the file but I didn’t understand what any of that meant. So I would load the gearbox mod with pb3.0 and then while playing, open the console and type “py_weaponwheel_freeze CVar” ?  I apologize, I just don’t know what to do.

**Comment by mmaulwurff** [comment]
Known issue,  JMartinez9820 is right.

Go to main menu -> Project Brutality -> Gameplay Settings -> Weapon Special Wheel Freezes Time -> set it to Off.

Or open the console and type `py_weaponwheel_freeze false`

**Comment by JMartinez9820** [comment]
@Matty4818 Like what mmaulwurff said, Go to Project Brutality Settings -> Gameplay Settings -> Weapon Special Wheel Freezes Time. Turn that option off. Or enter py_weaponwheel_freeze false in the console
